[simulation]
increment = 60
time = 540000
celestialBodies = 4
showLabels = "true"

[body1]
name = "Earth"
x = 0
y = 0
z = 0
xVel = 0
yVel = 0
zVel = 0
mass = 5.97e24

[body2]
name = "ISS"
x = 6790029
y = 0
z = 0
xVel = 0
yVel = 7600
zVel = 0
mass = 450000

[body3]
name = "Satellite"
x = 7138100
y = 0
z = 0
xVel = 0
yVel = 7473.72303
zVel = 0
mass = 1e8

[body4]
name = "Hubble Space Telescope"
x = 6902152
y = 0
z = 0
xVel = 0
yVel = 7598
zVel = 0
mass = 12246.994
