#!/bin/sh
if [ $# -eq 0 ]; then
    echo "Output filename must be provided (e.g nbody.dat)."
    exit 1
fi

echo "Setting up virtual environment..."
if [ -d "venv/" ]; then
    source venv/bin/activate
else
    python3 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
fi

g++ compute/simulate.cpp -std=c++20 -o bin/simulate && ./bin/simulate $1
python visualize/visualize.py $1
deactivate
